project:
  type: website
  output-dir: docs

website:
  title: "Daria Khon"
  navbar:
    left:
      - text: "Portfolio"
        href: portfolio/listings.qmd

    # your social media handles
    right:
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/dariakhon/
      - icon: github
        text: GitHub
        href: https://github.com/dariakhv/
      - icon: medium
        text: Medium
        href: https://medium.com/@daria.khon


format:
  html:
    theme: sky
    css: styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
  

# search: 
#   location: navbar
#   type: textbox

# page-footer: 
#   left: |
#     <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
#   center: |
#     <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
#   right: |
#     <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>


